package constant

const (
	//A

	ACTIVITY_CALLBACK 						= "CALLBACK_ACTIVATION"
	ACTIVITY_SIGN_DOC 						= "SIGN_DOC"
	ACTIVITY_SEND_DOC 						= "SEND_DOC"
	ACTIVITY_CALLBACK_SEND_DOC 				= "CALLBACK_SEND_DOC"
	ACTIVITY_REGISTER 						= "REGISTER"
	ACTIVITY_ACTIVATION 					= "ACTIVATION"
)